### ISSUE TITLE
lords_attendance() not returning recent data unless sessionID named

### ISSUE THREAD

**Issue by pssguy** [evanodell/hansard#8]
```
x <- lords_attendance(session_id = NULL, start_date = "2017-02-01")
y <- lords_attendance(session_id = 725652, start_date = "2017-02-01")
identical(x,y) #FALSE
```
x has 0 obs, y has 1
It does not appear to be a problem prior to the start date. I am using v 0.5.4.9002 but same result with earlier, CRAN, version

ps   It is not clear in documentation why is there also an equivalent  hansard_lords_attendance() function

**Comment by evanodell** [comment]
Sorry for the delay in dealing with this. I've now deprecated `lords_attendance()`, which really was not up to the tasks required of it, in favour of `lords_attendance_session()` and `lords_attendance_date()`. I've also added `lords_sessions()` which accepts `start_date` and `end_date` parameters. This is all available in 0.5.5, which I've just pushed to GitHub. The data this returns is still rather messy and doesn't contain much information on the peers themselves, but it is still usable. I am exploring options for tidying it within the `hansard` package.

And the `hansard_` prefix is because many of the function names themselves are not very informative and could easily clash with functions in other packages (e.g. `bills()` is not very informative nor is it a term unique to the British parliament).  I'll try to make this clearer in the documentation.

It's also worth noting the API does not appear to currently have data on lords attendance after 2017-01-31.
